-- ════════════════════════════════════════════════════════════════════
-- FylePro GST — seed (clean slate)
--
-- No demo/dummy tenant is created. Real tenants, users, companies and GST
-- registrations are created through onboarding:
--
--   Login page → "New user?" → temporary credentials  new / new123
--   → add your real GSTIN(s) → create admin → finish.
--
-- The temporary onboarding credential (new / new123) is inserted by
-- schema.sql. Re-running schema.sql is safe and idempotent.
--
-- To wipe previously-seeded demo data from an existing database, see the
-- cleanup snippet in the project notes / chat.
-- ════════════════════════════════════════════════════════════════════
